name: desafio-picpay-simplificado

services:
  pg:
    image: bitnami/postgresql:13.6.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
